# Generated by Django 3.2 on 2021-05-26 21:06

from django.db import migrations, models
import meme.models


class Migration(migrations.Migration):

    dependencies = [
        ('meme', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='posts/default.jpg', upload_to=meme.models.upload_to, verbose_name='Image'),
        ),
    ]
