# Generated by Django 3.2 on 2021-05-26 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meme', '0004_remove_post_excerpt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
